#!/usr/bin/env python3
"""Construye el directorio general de oportunidades educativas de MaterIA Gris V34.

El archivo no intenta reunir todas las becas de internet. Integra rutas públicas
oficiales que ayudan a estudiar, financiarse, postularse o prepararse, y conserva
el estado observado al 16 de julio de 2026.
"""

from __future__ import annotations

import json
from collections import Counter
from datetime import date
from pathlib import Path
from urllib.parse import urlparse


ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / "public"
OUTPUT = PUBLIC / "oportunidades-antioquia.json"
AS_OF = date(2026, 7, 16)


def route(
    id_: str,
    title: str,
    provider: str,
    route_type: str,
    status: str,
    status_label: str,
    scope: str,
    territory: str,
    level: str,
    audience: str,
    benefit: str,
    deadline: str,
    source_url: str,
    source_title: str,
    decision_use: str,
    caveat: str,
    *,
    start_date: str | None = None,
    end_date: str | None = None,
    internal_href: str | None = None,
    tags: list[str] | None = None,
) -> dict:
    return {
        "id": id_,
        "title": title,
        "provider": provider,
        "route_type": route_type,
        "status": status,
        "status_label": status_label,
        "scope": scope,
        "territory": territory,
        "level": level,
        "audience": audience,
        "benefit": benefit,
        "deadline": deadline,
        "start_date": start_date,
        "end_date": end_date,
        "as_of": AS_OF.isoformat(),
        "source_url": source_url,
        "source_title": source_title,
        "internal_href": internal_href,
        "decision_use": decision_use,
        "caveat": caveat,
        "tags": tags or [],
        "source_domain": urlparse(source_url).netloc,
    }


def main() -> None:
    atlas = json.loads((PUBLIC / "datos.json").read_text(encoding="utf-8"))
    cgem = json.loads((PUBLIC / "oferta-gilberto-echeverri.json").read_text(encoding="utf-8"))

    routes = [
        route(
            "oferta-snies-antioquia",
            "Oferta académica activa en Antioquia",
            "Ministerio de Educación Nacional · SNIES",
            "Estudiar",
            "permanente",
            "Consulta permanente",
            "Departamental",
            "Antioquia · 51 municipios con oferta activa",
            "Técnica profesional, tecnológica, universitaria y posgrado",
            "Personas que comparan qué estudiar, dónde y en qué modalidad",
            f"{len(atlas['programas']):,} programas activos en el corte comparable 2024-II".replace(",", "."),
            "Sin fecha única; cada IES administra su admisión",
            "https://snies.mineducacion.gov.co/portal/ESTADISTICAS/Bases-consolidadas/",
            "Bases consolidadas SNIES",
            "Use Modo Decisión para reducir opciones y luego confirme admisión, costo y registro en la IES.",
            "El corte comparable departamental es 2024-II. Programa activo en SNIES no significa convocatoria abierta hoy.",
            internal_href="#decidir",
            tags=["programas", "IES", "modalidad", "territorio"],
        ),
        route(
            "ies-distrito-2026-2",
            "Oferta 2026-2 de las tres IES del Distrito",
            "Distrito de Medellín · ITM, Pascual Bravo y Colmayor",
            "Estudiar",
            "cerrada",
            "Inscripciones cerradas",
            "Distrital",
            "Medellín",
            "Pregrado y posgrado",
            "Aspirantes a la oferta pública distrital",
            "Más de 12.200 cupos anunciados para 2026-2",
            "Los cierres de inscripción fueron entre el 15 y el 17 de junio de 2026",
            "https://www.medellin.gov.co/es/sala-de-prensa/noticias/hay-mas-de-12-200-cupos-disponibles-para-estudiar-desde-el-segundo-semestre-pregrado-y-posgrado-en-medellin/",
            "Convocatoria distrital 2026-2",
            "Consulte el capítulo distrital para comparar oferta, matrícula, calidad y finanzas y vigile el próximo calendario institucional.",
            "Cupos anunciados no equivalen a matriculados. El ciclo 2026-2 ya cerró inscripciones al corte.",
            end_date="2026-06-17",
            internal_href="#distrito",
            tags=["ITM", "Pascual Bravo", "Colmayor", "cupos"],
        ),
        route(
            "matricula-cero-medellin-2026-2",
            "Matrícula Cero Medellín 2026-2",
            "Sapiencia · Distrito de Medellín",
            "Financiarse",
            "abierta",
            "Abierta",
            "Distrital",
            "Medellín",
            "Técnica profesional, tecnología y profesional",
            "Personas nacidas en Medellín o con residencia demostrable durante el año previo, admitidas o matriculadas en IES públicas elegibles con sede en Medellín",
            "Hasta 100 % de la liquidación de matrícula; mínimo ocho créditos",
            "21 de agosto de 2026 · 4:00 p. m.",
            "https://sapiencia.gov.co/matricula-cero/",
            "Matrícula Cero · convocatoria 2026-2",
            "Es la principal ruta abierta de financiación pública local al corte. Primero confirme admisión y convenio de la IES.",
            "La postulación no garantiza el beneficio. Aplican requisitos, impedimentos, disponibilidad de recursos y validación de información.",
            start_date="2026-07-06",
            end_date="2026-08-21",
            tags=["beca", "matrícula", "pregrado", "Medellín"],
        ),
        route(
            "puedo-estudiar-gratuidad",
            "Política de gratuidad Puedo Estudiar",
            "Ministerio de Educación Nacional",
            "Financiarse",
            "permanente",
            "Ruta por matrícula",
            "Nacional",
            "IES públicas con oferta en Antioquia",
            "Pregrado",
            "Estudiantes de IES públicas que cumplan las condiciones socioeconómicas o poblacionales y no tengan título profesional universitario",
            "Matrícula ordinaria neta de pregrado según reporte y validación de la IES",
            "Depende del calendario de admisión y matrícula de cada IES pública",
            "https://www.mineducacion.gov.co/portal//419532:Informacion-de-Interes-Politica-de-Gratuidad",
            "Política de Gratuidad en la Matrícula",
            "El acceso comienza con la admisión y matrícula en una IES pública; no es una beca que se solicite en un formulario nacional independiente.",
            "La IES reporta y valida la información. La política no cubre automáticamente derechos pecuniarios u otros costos distintos de la matrícula ordinaria neta.",
            tags=["gratuidad", "IES pública", "pregrado"],
        ),
        route(
            "sapiencia-pregrados-2026-2",
            "Fondos Sapiencia para pregrado",
            "Sapiencia · Distrito de Medellín",
            "Financiarse",
            "legalizacion",
            "Preselección y legalización",
            "Distrital",
            "Medellín y Valle de Aburrá según reglamento",
            "Técnica profesional, tecnología y profesional",
            "Personas preseleccionadas en la convocatoria 2026-2 de créditos condonables",
            "Crédito condonable mediante Presupuesto Participativo y recursos ordinarios",
            "La página oficial publica preselección y ruta de legalización 2026-2",
            "https://sapiencia.gov.co/fondos-sapiencia/pregrados/",
            "Fondos Sapiencia · Pregrados",
            "Úselo para verificar resultados, documentación y condiciones de condonación; no como una convocatoria nueva abierta.",
            "Crédito condonable no es beca automática ni gratuidad. La fuente de recursos y las condiciones cambian por territorio y convocatoria.",
            tags=["crédito condonable", "pregrado", "Presupuesto Participativo"],
        ),
        route(
            "sapiencia-posgrados-nacionales-2026-2",
            "Fondo Sapiencia Posgrados Nacionales",
            "Sapiencia · Distrito de Medellín",
            "Financiarse",
            "legalizacion",
            "Preselección y legalización",
            "Distrital",
            "Medellín",
            "Maestría, doctorado y posdoctorado",
            "Personas preseleccionadas para cofinanciar posgrados nacionales",
            "Crédito condonable sujeto a factores académicos y transferencia de conocimiento",
            "La página oficial publica resolución de preselección y citas de legalización 2026-2",
            "https://sapiencia.gov.co/fondos-sapiencia/posgrados_nacionales/",
            "Fondo Sapiencia Posgrados Nacionales",
            "Permite seguir la fase vigente y preparar evidencia de legalización o una próxima convocatoria.",
            "La condonación depende del reglamento y del cumplimiento de compromisos; no equivale a una beca integral concedida al postularse.",
            tags=["posgrado", "crédito condonable", "Medellín"],
        ),
        route(
            "icetex-tu-eliges-30-2026-2",
            "ICETEX Tú Eliges 30 % · 2026-2",
            "ICETEX",
            "Financiarse",
            "abierta",
            "Abierta",
            "Nacional",
            "Colombia · aplicable en IES de Antioquia",
            "Pregrado",
            "Aspirantes que requieran crédito educativo y cumplan las condiciones de la línea",
            "Crédito: pago del 30 % durante estudios y saldo después de graduarse según condiciones",
            "31 de julio de 2026; el formulario puede cerrar antes si se agotan recursos",
            "https://web.icetex.gov.co/calendario-de-pregrado",
            "Calendario de pregrado ICETEX 2026-2",
            "Compare costo total, tasa, plazo y capacidad de pago antes de usar esta ruta como complemento de becas o gratuidad.",
            "Es crédito, no beca. La aprobación y el calendario están sujetos a verificación y disponibilidad de recursos.",
            start_date="2026-05-25",
            end_date="2026-07-31",
            tags=["crédito", "pregrado", "nacional"],
        ),
        route(
            "icetex-medicina-40-2026-2",
            "ICETEX Medicina 40 % · 2026-2",
            "ICETEX",
            "Financiarse",
            "cierra_pronto",
            "Cierra pronto",
            "Nacional",
            "Colombia · aplicable en IES de Antioquia",
            "Medicina",
            "Aspirantes a medicina que cumplan condiciones de la línea",
            "Crédito educativo con pago del 40 % durante estudios según condiciones",
            "17 de julio de 2026",
            "https://web.icetex.gov.co/calendario-de-pregrado",
            "Calendario de pregrado ICETEX 2026-2",
            "La cercanía del cierre exige confirmar inmediatamente formulario, documentos y costos de largo plazo.",
            "Es crédito, no beca; la fecha y disponibilidad deben confirmarse directamente antes de iniciar el trámite.",
            end_date="2026-07-17",
            tags=["crédito", "medicina", "cierre"],
        ),
        route(
            "jovenes-pa-lante-2026",
            "Becas Jóvenes Pa’ Lante Antioquia 2026",
            "Gobernación de Antioquia · Corporación Gilberto Echeverri Mejía",
            "Financiarse",
            "legalizacion",
            "Legalización y matrícula",
            "Departamental",
            "78 municipios con combinaciones publicadas en nueve subregiones",
            "Educación para el Trabajo y el Desarrollo Humano",
            "Personas inscritas y elegibles de municipios no certificados, según reglamento",
            "100 % de matrícula y apoyo de hasta $530.000; 10.000 becas anunciadas",
            "Legalización y matrícula programada del 17 de julio al 16 de agosto de 2026",
            "https://corporaciongilbertoecheverri.gov.co/becas-jovenes-pa-lante-antioquia/",
            "Becas Jóvenes Pa’ Lante Antioquia",
            "Consulte requisitos y el detalle de las 165 combinaciones de sede, institución y programa ya estructuradas por MaterIA.",
            "La convocatoria cerró. Las 165 filas no son cupos ni matrículas y la apertura de grupos depende de condiciones operativas.",
            start_date="2026-07-17",
            end_date="2026-08-16",
            internal_href="oferta-gilberto-echeverri.json",
            tags=["beca", "ETDH", "municipios", "Corporación Gilberto Echeverri"],
        ),
        route(
            "supere-envigado-2026-2",
            "Programa de estímulos Superé · Envigado 2026-2",
            "Municipio de Envigado · Corporación Gilberto Echeverri Mejía",
            "Financiarse",
            "legalizacion",
            "Legalización en curso",
            "Municipal",
            "Envigado",
            "Educación superior",
            "Personas preseleccionadas del municipio que cumplan el reglamento",
            "Estímulo educativo administrado mediante fondo municipal",
            "Legalización hasta el 22 de julio; resultados previstos el 6 de agosto de 2026",
            "https://corporaciongilbertoecheverri.gov.co/programa-de-estimulos-supere/",
            "Programa de estímulos Superé",
            "Muestra cómo un fondo municipal complementa las rutas departamentales, distritales y nacionales.",
            "La fase vigente corresponde a legalización de preseleccionados; no es una nueva inscripción abierta.",
            end_date="2026-07-22",
            tags=["Envigado", "fondo municipal", "estímulo"],
        ),
        route(
            "semestre-cero-antioquia-2026",
            "Semestre Cero Antioquia 2026",
            "Gobernación de Antioquia · Corporación Gilberto Echeverri Mejía",
            "Prepararse",
            "en_curso",
            "En ejecución",
            "Departamental",
            "61 municipios · 16 rurales dispersos",
            "Grado 11 y transición media–superior",
            "4.247 estudiantes de grado 11 en 76 instituciones educativas",
            "Fortalecimiento de competencias para ingreso y permanencia; inversión reportada de $5.926 millones",
            "Ejecución entre abril y septiembre de 2026",
            "https://www.antioquia.gov.co/index.php/antioquiacuenta/semestre-cero-impulsa-la-educacion-superior-de-mas-de-4-mil-200-jovenes-en-antioquia",
            "Semestre Cero 2026",
            "Sirve para analizar transición, preparación y presencia territorial antes de la matrícula superior.",
            "Participantes e inversión reportada no equivalen a ingreso posterior a educación superior; hace falta seguimiento de cohortes.",
            start_date="2026-04-01",
            end_date="2026-09-30",
            tags=["grado 11", "transición", "municipios"],
        ),
        route(
            "educacion-superior-en-tu-colegio",
            "Educación Superior en tu Colegio",
            "Ministerio de Educación Nacional · IES aliadas",
            "Prepararse",
            "en_curso",
            "Programa en desarrollo",
            "Departamental",
            "Instituciones educativas articuladas en Antioquia",
            "Media y formación técnica profesional o tecnológica",
            "Estudiantes de educación media de colegios vinculados al programa",
            "Trayectorias de formación superior iniciadas desde el colegio",
            "Depende de convenios, institución educativa e IES operadora",
            "https://www.mineducacion.gov.co/portal/micrositios-institucionales/Regiones/424404:Antioquia",
            "Balance territorial de educación en Antioquia",
            "Permite observar articulación media–superior como capacidad del sistema, no solo como convocatoria individual.",
            "La cobertura se define por convenios institucionales; la publicación no constituye una inscripción general para cualquier estudiante.",
            tags=["colegio", "media", "articulación", "TyT"],
        ),
        route(
            "oportunidades-juventud-antioquia",
            "Directorio Oportunidades Juventud",
            "Gobernación de Antioquia",
            "Postularse",
            "permanente",
            "Directorio periódico",
            "Departamental y externo",
            "Antioquia · oportunidades nacionales e internacionales",
            "Cursos, becas, convocatorias y empleo",
            "Jóvenes que buscan una puerta de entrada a convocatorias de distintos promotores",
            "Directorio informativo actualizado por la Gobernación",
            "Cada oportunidad conserva su propio calendario",
            "https://www.antioquia.gov.co/index.php/oportunidades-juventud/oportunidades-juventud-junio-2026",
            "Oportunidades Juventud · junio de 2026",
            "Úselo para ampliar la búsqueda más allá de las rutas sistematizadas por MaterIA y verifique siempre al promotor.",
            "La Gobernación aclara que la información es orientativa y que cada entidad promotora responde por requisitos, vigencia y selección.",
            tags=["directorio", "jóvenes", "convocatorias", "cursos"],
        ),
        route(
            "ingles-para-el-trabajo-2026",
            "Becas Inglés para el Trabajo 2026",
            "Gobernación de Antioquia · Colombo Americano",
            "Prepararse",
            "cerrada",
            "Convocatoria cerrada",
            "Departamental",
            "Urabá y resto de Antioquia, excepto Medellín",
            "Formación complementaria",
            "Personas que buscaban fortalecer inglés para empleabilidad",
            "2.000 becas anunciadas; clases virtuales sincrónicas en módulos de 50 horas",
            "La convocatoria cerró el 1 de marzo de 2026",
            "https://www.antioquia.gov.co/index.php/antioquiacuenta/la-gobernacion-de-antioquia-en-alianza-con-el-colombo-americano-abre-la-convocatoria-para-becas-de-ingles-para-el-trabajo",
            "Convocatoria Inglés para el Trabajo",
            "Conserva evidencia de una capacidad de formación complementaria y permite vigilar una próxima edición.",
            "Las becas anunciadas no equivalen a personas certificadas. El ciclo de inscripción ya cerró.",
            end_date="2026-03-01",
            tags=["inglés", "empleabilidad", "Urabá"],
        ),
    ]

    allowed_statuses = {"abierta", "cierra_pronto", "legalizacion", "en_curso", "permanente", "cerrada"}
    allowed_types = {"Estudiar", "Financiarse", "Postularse", "Prepararse"}
    assert len({item["id"] for item in routes}) == len(routes)
    assert {item["route_type"] for item in routes} == allowed_types
    assert {item["status"] for item in routes}.issubset(allowed_statuses)
    assert all(item["source_url"].startswith("https://") for item in routes)
    assert all(item["decision_use"] and item["caveat"] and item["audience"] for item in routes)

    by_type = Counter(item["route_type"] for item in routes)
    by_status = Counter(item["status"] for item in routes)
    current_statuses = {"abierta", "cierra_pronto", "legalizacion", "en_curso", "permanente"}
    current = sum(item["status"] in current_statuses for item in routes)
    payload = {
        "meta": {
            "title": "Oportunidades educativas de Antioquia · MaterIA Gris V34",
            "version": "V34",
            "generated_on": AS_OF.isoformat(),
            "as_of": AS_OF.isoformat(),
            "universe": "Rutas públicas oficiales identificables para estudiar, financiarse, postularse o prepararse, con relevancia para Antioquia.",
            "exclusions": "No incluye como exhaustivas las becas privadas, ofertas laborales, publicaciones sin fuente oficial ni oportunidades cuya vigencia no pudo confirmarse.",
            "method": "Curaduría de páginas oficiales; cada ruta conserva proveedor, alcance, estado, fecha, uso decisional y cautela.",
        },
        "summary": {
            "routes": len(routes),
            "current_routes": current,
            "open_or_closing": by_status["abierta"] + by_status["cierra_pronto"],
            "route_types": len(by_type),
            "programs_in_atlas": len(atlas["programas"]),
            "institutions_in_atlas": len(atlas["ies"]),
            "municipalities_with_active_offer": len(atlas["municipios"]),
            "cgem_offer_combinations": cgem["summary"]["offer_combinations"],
            "by_type": dict(sorted(by_type.items())),
            "by_status": dict(sorted(by_status.items())),
        },
        "status_order": ["abierta", "cierra_pronto", "legalizacion", "en_curso", "permanente", "cerrada"],
        "route_types": [
            {"id": "Estudiar", "title": "Estudiar", "description": "Comparar programas, instituciones, sedes y ciclos de admisión.", "symbol": "01"},
            {"id": "Financiarse", "title": "Financiarse", "description": "Distinguir gratuidad, beca, estímulo y crédito condonable o reembolsable.", "symbol": "02"},
            {"id": "Postularse", "title": "Postularse", "description": "Priorizar convocatorias por estado y fecha sin confundir publicación con selección.", "symbol": "03"},
            {"id": "Prepararse", "title": "Prepararse", "description": "Reconocer rutas de transición, competencias e idiomas antes o durante el acceso.", "symbol": "04"},
        ],
        "routes": routes,
        "trust_rules": [
            "La fuente oficial manda: confirme vigencia, requisitos y enlace antes de entregar documentos.",
            "Beca, gratuidad, crédito condonable y crédito reembolsable no son sinónimos.",
            "Cupo anunciado, postulación, preselección, legalización, matrícula y graduación son etapas distintas.",
            "MaterIA organiza la evidencia, pero no recibe postulaciones ni garantiza selección.",
        ],
        "related_datasets": [
            {"title": "Oferta académica comparable", "href": "datos.json", "role": "2.107 programas activos SNIES 2024-II"},
            {"title": "IES públicas del Distrito", "href": "ies-distritales.json", "role": "oferta, matrícula, calidad y finanzas"},
            {"title": "Detalle Jóvenes Pa’ Lante", "href": "oferta-gilberto-echeverri.json", "role": "165 combinaciones dentro de una de las rutas"},
            {"title": "Fuentes vivas", "href": "fuentes-antioquia.json", "role": "indicadores y metadatos del diagnóstico"},
        ],
    }
    OUTPUT.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"output": str(OUTPUT), **payload["summary"]}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
