#!/usr/bin/env python3
"""Construye el registro público de fuentes e indicadores de Antioquia.

El archivo resultante no intenta fabricar un único corte. Conserva el periodo,
el universo, el territorio y el tipo de evidencia de cada cifra para que la
interfaz pueda impedir sumas o comparaciones inválidas.
"""

from __future__ import annotations

import json
from collections import Counter
from datetime import date
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "public" / "fuentes-antioquia.json"
CUT = date(2026, 7, 24)


SOURCES = [
    {
        "id": "snies-bases-2024",
        "institution": "Ministerio de Educación Nacional · SNIES",
        "title": "Bases consolidadas de educación superior",
        "source_type": "oficial",
        "publication_date": "2025",
        "data_cut": "2024-II",
        "territory": "Antioquia",
        "level": "Educación superior",
        "url": "https://snies.mineducacion.gov.co/portal/ESTADISTICAS/Bases-consolidadas/",
        "role": "Base comparable para matrícula, instituciones y lugares de oferta.",
        "refresh": "Anual",
    },
    {
        "id": "snies-cronograma-2026",
        "institution": "Ministerio de Educación Nacional · SNIES",
        "title": "Calendario oficial de publicación estadística 2026",
        "source_type": "oficial",
        "publication_date": "2026",
        "data_cut": "Programación 2026",
        "territory": "Colombia",
        "level": "Educación superior",
        "url": "https://snies.mineducacion.gov.co/1778/w3-article-391228.html?_noredirect=1",
        "role": "Documenta el calendario previsto; el agregado nacional 2025 se publicó el 15 de julio, antes de la ventana anunciada.",
        "refresh": "Calendario 2026",
    },
    {
        "id": "snies-national-2025",
        "institution": "Ministerio de Educación Nacional · SNIES",
        "title": "Resultado agregado nacional de educación superior 2025",
        "source_type": "oficial",
        "publication_date": "2026-07-15",
        "data_cut": "2025 · agregado nacional",
        "territory": "Colombia",
        "level": "Educación superior",
        "url": "https://www.mineducacion.gov.co/portal/salaprensa/Comunicados/429538:SNIES-confirma-record-historico-Colombia-supera-por-primera-vez-los-2-7-millones-de-estudiantes-en-educacion-superior",
        "role": "Actualiza escala y cobertura nacional sin anticipar resultados departamentales.",
        "refresh": "Anual",
    },
    {
        "id": "men-antioquia-2026",
        "institution": "Ministerio de Educación Nacional",
        "title": "Balance territorial de educación en Antioquia",
        "source_type": "oficial",
        "publication_date": "2026-01-23",
        "data_cut": "2025-1 y balance frente a 2022",
        "territory": "Antioquia",
        "level": "Educación superior",
        "url": "https://www.mineducacion.gov.co/portal/micrositios-institucionales/Regiones/424404:Antioquia",
        "role": "Señales administrativas de gratuidad, nuevo ingreso y articulación con colegios.",
        "refresh": "Eventual",
    },
    {
        "id": "gob-aulas-2026",
        "institution": "Gobernación de Antioquia · Secretaría de Educación",
        "title": "Inicio del segundo semestre escolar 2026",
        "source_type": "oficial",
        "publication_date": "2026-07-05",
        "data_cut": "2026-II",
        "territory": "116 municipios no certificados",
        "level": "Preescolar, básica y media",
        "url": "https://www.antioquia.gov.co/index.php/secretaria-educacion/cerca-de-430-mil-estudiantes-regresan-a-las-aulas-para-iniciar-el-segundo-semestre-del-calendario-escolar-en-antioquia",
        "role": "Dimensiona la base escolar administrada por el departamento.",
        "refresh": "Semestral",
    },
    {
        "id": "gob-conectividad-2026",
        "institution": "Gobernación de Antioquia",
        "title": "Conectividad satelital y fibra óptica educativa",
        "source_type": "oficial",
        "publication_date": "2026-06-24",
        "data_cut": "Acumulado a junio de 2026",
        "territory": "Antioquia",
        "level": "Preescolar, básica y media",
        "url": "https://www.antioquia.gov.co/index.php/antioquiacuenta/antioquia-supera-los-3-mil-400-puntos-de-conexion-a-internet-mediante-antenas-satelitales-y-fibra-optica",
        "role": "Mide infraestructura habilitante en sedes educativas urbanas y rurales.",
        "refresh": "Eventual",
    },
    {
        "id": "gob-semestre-cero-2026",
        "institution": "Gobernación de Antioquia · Corporación Gilberto Echeverri Mejía",
        "title": "Semestre Cero 2026",
        "source_type": "oficial",
        "publication_date": "2026-04-21",
        "data_cut": "2026",
        "territory": "61 municipios",
        "level": "Transición media–superior",
        "url": "https://www.antioquia.gov.co/index.php/antioquiacuenta/semestre-cero-impulsa-la-educacion-superior-de-mas-de-4-mil-200-jovenes-en-antioquia",
        "role": "Describe escala, presencia territorial e inversión del programa de preparación.",
        "refresh": "Anual",
    },
    {
        "id": "gob-gestion-educacion-2025",
        "institution": "Gobernación de Antioquia · Secretaría de Educación",
        "title": "Informe de gestión 2025",
        "source_type": "oficial",
        "publication_date": "2026",
        "data_cut": "2024 y balance 2025",
        "territory": "Antioquia",
        "level": "Educación superior",
        "url": "https://antioquia.gov.co/images/rendicion-de-cuentas/2026/informe-de-gestion-2025.pdf",
        "role": "Reporta cobertura departamental, cambio de matrícula y tránsito inmediato en municipios no certificados.",
        "refresh": "Anual",
    },
    {
        "id": "agenda-antioquia-2040-2025",
        "institution": "Gobernación de Antioquia · Agenda Antioquia 2040",
        "title": "Seguimiento al avance de la Agenda Antioquia 2040",
        "source_type": "oficial",
        "publication_date": "2025-09",
        "data_cut": "2024 · corte de seguimiento",
        "territory": "Antioquia sin Valle de Aburrá",
        "level": "Educación superior",
        "url": "https://antioquia.gov.co/images/PDF2/Transparencia/2025/09/seguimiento-avance-agenda-2040-05082025.pdf",
        "role": "Aporta una lectura territorial provisional de cobertura fuera del Valle de Aburrá.",
        "refresh": "Periódica",
    },
    {
        "id": "cgem-offer-2026",
        "institution": "Corporación Gilberto Echeverri Mejía",
        "title": "Oferta académica de Becas Jóvenes Pa'Lante 2026",
        "source_type": "oficial",
        "publication_date": "2026-07-09",
        "data_cut": "Oferta vigente publicada el 9 de julio de 2026",
        "territory": "Nueve subregiones de Antioquia",
        "level": "Educación para el Trabajo y el Desarrollo Humano",
        "url": "https://corporaciongilbertoecheverri.gov.co/wp-content/uploads/2026/07/Oferta-Academica-09Jul26.pdf",
        "role": "Permite buscar combinaciones de sede, institución, área y programa.",
        "refresh": "Durante la convocatoria",
    },
    {
        "id": "cgem-budget-2026",
        "institution": "Corporación Gilberto Echeverri Mejía",
        "title": "Presupuesto inicial de ingresos y gastos 2026",
        "source_type": "oficial",
        "publication_date": "2026-01-05",
        "data_cut": "Vigencia fiscal 2026",
        "territory": "Antioquia",
        "level": "Financiación educativa",
        "url": "https://corporaciongilbertoecheverri.gov.co/wp-content/uploads/2026/03/Acuerdo-01-de-2025-Aprobacion-presupuesto-2026_-1.pdf",
        "role": "Dimensiona la apropiación inicial para becas, Semestre Cero, Fondo de Educación Superior y funcionamiento.",
        "refresh": "Anual y por modificaciones",
    },
    {
        "id": "gob-palante-2026",
        "institution": "Gobernación de Antioquia · Corporación Gilberto Echeverri Mejía",
        "title": "Convocatoria Becas Jóvenes Pa'Lante 2026",
        "source_type": "oficial",
        "publication_date": "2026-06",
        "data_cut": "Convocatoria 2026",
        "territory": "Antioquia",
        "level": "Educación para el Trabajo y el Desarrollo Humano",
        "url": "https://www.antioquia.gov.co/index.php/antioquiacuenta/gobernacion-de-antioquia-abre-nueva-convocatoria-de-becas-jovenes-pa-lante-para-impulsar-el-acceso-a-la-educacion-superior",
        "role": "Documenta meta anunciada, requisitos generales y operación del programa.",
        "refresh": "Por convocatoria",
    },
    {
        "id": "gob-palante-2025",
        "institution": "Gobernación de Antioquia · Corporación Gilberto Echeverri Mejía",
        "title": "Cierre de inscripciones de Becas Jóvenes Pa'Lante 2025",
        "source_type": "oficial",
        "publication_date": "2025-08-03",
        "data_cut": "Convocatoria 2025 · cierre de inscripciones",
        "territory": "123 municipios de Antioquia",
        "level": "Educación para el Trabajo y el Desarrollo Humano",
        "url": "https://www.antioquia.gov.co/index.php/antioquiacuenta/todo-un-exito-mas-de-7-mil-jovenes-se-inscribieron-a-la-convocatoria-del-programa-becas-jovenes-pa-lante-antioquia-de-formacion-para-el-empleo",
        "role": "Describe demanda de la convocatoria; no sustituye el número final de matriculados.",
        "refresh": "Por convocatoria",
    },
    {
        "id": "proantioquia-capacidades-2026",
        "institution": "Proantioquia",
        "title": "Capacidades educativas y culturales",
        "source_type": "observatorio",
        "publication_date": "2026",
        "data_cut": "2025 y agenda 2026",
        "territory": "Antioquia",
        "level": "Trayectorias educativas",
        "url": "https://proantioquia.org.co/capacidades-educativas-y-culturales/",
        "role": "Aporta iniciativas privadas, cobertura territorial y vacíos de transición.",
        "refresh": "Continua",
    },
    {
        "id": "proantioquia-inversion-2025",
        "institution": "Proantioquia · Mesa Fundación de Fundaciones",
        "title": "Inversión privada en educación · balance 2025",
        "source_type": "observatorio",
        "publication_date": "2026-02-27",
        "data_cut": "2025",
        "territory": "Nueve subregiones de Antioquia",
        "level": "Sistema educativo",
        "url": "https://proantioquia.org.co/download/inversion-privada-en-educacion-balance-2025/",
        "role": "Sistematiza inversión autorreportada por organizaciones privadas.",
        "refresh": "Anual",
    },
    {
        "id": "proantioquia-valle-aburra-2026",
        "institution": "Proantioquia",
        "title": "Caracterización del sector educativo del Valle de Aburrá",
        "source_type": "observatorio",
        "publication_date": "2026-03-09",
        "data_cut": "2025",
        "territory": "Valle de Aburrá",
        "level": "Preescolar, básica y media",
        "url": "https://proantioquia.org.co/download/caracterizacion-y-perfil-de-sector-educativo-valle-de-aburra/",
        "role": "Perfila matrícula, sedes, sector y localización urbana de la principal subregión.",
        "refresh": "Anual",
    },
    {
        "id": "medellin-plan-2026",
        "institution": "Distrito de Medellín · Sapiencia",
        "title": "Seguimiento al Plan Indicativo",
        "source_type": "oficial",
        "publication_date": "2026-04",
        "data_cut": "2026-02-28",
        "territory": "Medellín · tres IES distritales",
        "level": "Educación superior",
        "url": "https://www.medellin.gov.co/es/wp-content/uploads/2026/04/Sgto_PI_28Feb2026.pdf",
        "role": "Corte administrativo de matrícula, calidad, investigación y articulación.",
        "refresh": "Periódica",
    },
    {
        "id": "medellin-matricula-cero-2026",
        "institution": "Distrito de Medellín · Sapiencia",
        "title": "Matrícula Cero 2026-1",
        "source_type": "oficial",
        "publication_date": "2025-12-19",
        "data_cut": "Convocatoria 2026-1",
        "territory": "Medellín · ocho IES públicas",
        "level": "Educación superior",
        "url": "https://www.medellin.gov.co/es/sala-de-prensa/noticias/matricula-cero-trae-46-667-oportunidades-en-educacion-superior-para-el-primer-semestre-de-2026/",
        "role": "Registra beneficios proyectados y recursos anunciados; no matrícula ejecutada.",
        "refresh": "Semestral",
    },
    {
        "id": "minciencias-957-2025",
        "institution": "Ministerio de Ciencia, Tecnología e Innovación",
        "title": "Resultados finales de la Convocatoria 957 de 2024",
        "source_type": "oficial",
        "publication_date": "2025-12-05",
        "data_cut": "Convocatoria 957 de 2024",
        "territory": "Colombia",
        "level": "Investigación",
        "url": "https://minciencias.gov.co/convocatorias/investigacion/convocatoria-nacional-actualizacion-y-transicion-para-el-reconocimiento",
        "role": "Lista oficial de grupos reconocidos; MaterIA deriva la ubicación departamental.",
        "refresh": "Por convocatoria",
    },
    {
        "id": "acv-icv-2024",
        "institution": "Antioquia Cómo Vamos",
        "title": "Informe de Calidad de Vida de Antioquia 2024",
        "source_type": "observatorio",
        "publication_date": "2025-09-11",
        "data_cut": "Series con disponibilidad hasta 2024",
        "territory": "Antioquia",
        "level": "Sistema educativo",
        "url": "https://www.antioquiacomovamos.org/wp-content/uploads/2025/09/20250911_ICV-2024.pdf",
        "role": "Contraste analítico de MEN, DANE, ICFES, SNIES y LEA; no reemplaza las bases primarias.",
        "refresh": "Anual",
    },
    {
        "id": "sapiencia-matricula-cero-2026-2",
        "institution": "Sapiencia · Distrito de Medellín",
        "title": "Matrícula Cero 2026-2",
        "source_type": "oficial",
        "publication_date": "2026-07",
        "data_cut": "Convocatoria 2026-2",
        "territory": "Medellín",
        "level": "Pregrado",
        "url": "https://sapiencia.gov.co/matricula-cero/",
        "role": "Documenta calendario, financiación, requisitos, impedimentos e IES elegibles.",
        "refresh": "Semestral",
    },
    {
        "id": "sapiencia-pregrados-2026-2",
        "institution": "Sapiencia · Distrito de Medellín",
        "title": "Fondos Sapiencia para pregrado",
        "source_type": "oficial",
        "publication_date": "2026",
        "data_cut": "Preselección y legalización 2026-2",
        "territory": "Medellín y Valle de Aburrá según reglamento",
        "level": "Pregrado",
        "url": "https://sapiencia.gov.co/fondos-sapiencia/pregrados/",
        "role": "Distingue créditos condonables y publica la fase vigente de la convocatoria.",
        "refresh": "Semestral",
    },
    {
        "id": "sapiencia-posgrados-2026-2",
        "institution": "Sapiencia · Distrito de Medellín",
        "title": "Fondo Sapiencia Posgrados Nacionales",
        "source_type": "oficial",
        "publication_date": "2026",
        "data_cut": "Preselección y legalización 2026-2",
        "territory": "Medellín",
        "level": "Posgrado",
        "url": "https://sapiencia.gov.co/fondos-sapiencia/posgrados_nacionales/",
        "role": "Documenta cofinanciación, preselección y legalización de posgrados nacionales.",
        "refresh": "Semestral",
    },
    {
        "id": "icetex-pregrado-2026-2",
        "institution": "ICETEX",
        "title": "Calendario de crédito de pregrado 2026-2",
        "source_type": "oficial",
        "publication_date": "2026-06-30",
        "data_cut": "Convocatoria 2026-2",
        "territory": "Colombia",
        "level": "Pregrado",
        "url": "https://web.icetex.gov.co/calendario-de-pregrado",
        "role": "Permite separar líneas de crédito, fechas, documentos y resultados.",
        "refresh": "Semestral",
    },
    {
        "id": "men-gratuidad-2026",
        "institution": "Ministerio de Educación Nacional",
        "title": "Política de Gratuidad Puedo Estudiar",
        "source_type": "oficial",
        "publication_date": "2026-06-20",
        "data_cut": "Información vigente 2026",
        "territory": "Colombia",
        "level": "Pregrado público",
        "url": "https://www.mineducacion.gov.co/portal//419532:Informacion-de-Interes-Politica-de-Gratuidad",
        "role": "Aclara elegibilidad y la ruta de acceso a gratuidad mediante matrícula en IES públicas.",
        "refresh": "Según cambios normativos",
    },
    {
        "id": "gob-oportunidades-juventud-2026",
        "institution": "Gobernación de Antioquia",
        "title": "Directorio Oportunidades Juventud",
        "source_type": "oficial",
        "publication_date": "2026-06",
        "data_cut": "Directorio de junio de 2026",
        "territory": "Antioquia y oportunidades externas",
        "level": "Formación, becas, convocatorias y empleo",
        "url": "https://www.antioquia.gov.co/index.php/oportunidades-juventud/oportunidades-juventud-junio-2026",
        "role": "Amplía el radar de convocatorias y conserva la responsabilidad de cada promotor.",
        "refresh": "Mensual o periódico",
    },
    {
        "id": "men-matricula-basica-2024",
        "institution": "Ministerio de Educación Nacional · datos.gov.co",
        "title": "Matrícula de preescolar, básica y media por sede y municipio (ngw5-c5nw)",
        "source_type": "oficial",
        "publication_date": "2025-07-29",
        "data_cut": "2010-2024 (sin 2018)",
        "territory": "Antioquia",
        "level": "Preescolar, básica y media",
        "url": "https://www.datos.gov.co/resource/ngw5-c5nw",
        "role": "Microagregados por sede que permiten la serie municipal de matrícula, sectores oficial y no oficial.",
        "refresh": "Anual",
    },
    {
        "id": "men-tasas-ebm-2024",
        "institution": "Ministerio de Educación Nacional · datos.gov.co",
        "title": "Tasas de cobertura y deserción en preescolar, básica y media (ji8i-4anb)",
        "source_type": "oficial",
        "publication_date": "2025-11-13",
        "data_cut": "2011-2024",
        "territory": "Antioquia",
        "level": "Preescolar, básica y media",
        "url": "https://www.datos.gov.co/resource/ji8i-4anb",
        "role": "Fila departamental oficial de cobertura neta/bruta por nivel y deserción intraanual.",
        "refresh": "Anual",
    },
    {
        "id": "men-bachilleres-2024",
        "institution": "Ministerio de Educación Nacional · datos.gov.co",
        "title": "Bachilleres por entidad territorial certificada (5c2k-ahfc)",
        "source_type": "oficial",
        "publication_date": "2025-11-13",
        "data_cut": "2019-2024",
        "territory": "Antioquia · 10 ETC",
        "level": "Transición media–superior",
        "url": "https://www.datos.gov.co/resource/5c2k-ahfc",
        "role": "Cuenta la cosecha anual de bachilleres (grado 11 + CLEI) que alimenta la demanda de educación superior.",
        "refresh": "Anual",
    },
    {
        "id": "icetex-datos-abiertos-2026",
        "institution": "ICETEX · datos.gov.co",
        "title": "Créditos otorgados, renovados y cartera del ICETEX (26bn-e42j, nvcf-b8a3, dugh-vkir)",
        "source_type": "oficial",
        "publication_date": "2026-07-15",
        "data_cut": "Vigencias 2015-2025 · cartera al 2026-06-30",
        "territory": "Antioquia y Colombia",
        "level": "Financiación educativa",
        "url": "https://www.datos.gov.co/resource/26bn-e42j",
        "role": "Series de beneficiarios de crédito educativo y estado de la cartera por época.",
        "refresh": "Semestral (colocación) y trimestral (cartera)",
    },
    {
        "id": "gob-becas-2013-2024",
        "institution": "Gobernación de Antioquia · datos.gov.co",
        "title": "Becas de educación superior de la Gobernación (ya7f-466y)",
        "source_type": "oficial",
        "publication_date": "2024-05-20",
        "data_cut": "Convocatorias 2013-2024 (2024 parcial)",
        "territory": "Antioquia · 9 subregiones",
        "level": "Financiación educativa",
        "url": "https://www.datos.gov.co/resource/ya7f-466y",
        "role": "Historial de beneficiarios con subregión, estrato y estado de graduación.",
        "refresh": "Congelada desde mayo de 2024",
    },
    {
        "id": "sena-fpi-2024",
        "institution": "SENA · datos.gov.co",
        "title": "Formación profesional integral — aprendices, deserción y certificación (vv8g-8u9u, u4ze-bi7k, 28vu-5tx7)",
        "source_type": "oficial",
        "publication_date": "2024-03-14",
        "data_cut": "Fichas vigentes a febrero de 2024",
        "territory": "Regional Antioquia",
        "level": "Sistema educativo",
        "url": "https://www.datos.gov.co/resource/vv8g-8u9u",
        "role": "Registro administrativo propio del SENA: titulada y cursos largos con deserción por nivel.",
        "refresh": "Sin corte posterior publicado",
    },
    {
        "id": "ole-base-ibc-2023",
        "institution": "Ministerio de Educación Nacional · Observatorio Laboral para la Educación",
        "title": "Base IBC 2023 por programa e institución",
        "source_type": "oficial",
        "publication_date": "2024",
        "data_cut": "Cotizantes 2023 · graduados 2018-2022",
        "territory": "IES con domicilio en Antioquia",
        "level": "Educación superior",
        "url": "https://ole.mineducacion.gov.co/portal/",
        "role": "Permite el retorno salarial a nivel de programa, no solo por área.",
        "refresh": "Anual con rezago; sin corte 2024",
    },
]


def indicator(
    id_: str,
    title: str,
    value: float,
    display: str,
    unit: str,
    period: str,
    level: str,
    topic: str,
    territory: str,
    universe: str,
    source_id: str,
    evidence: str,
    decision_use: str,
    caveat: str,
) -> dict:
    return {
        "id": id_, "title": title, "value": value, "display": display,
        "unit": unit, "period": period, "level": level, "topic": topic,
        "territory": territory, "universe": universe, "source_id": source_id,
        "evidence": evidence, "decision_use": decision_use, "caveat": caveat,
    }


INDICATORS = [
    indicator("he-enrolment", "Matrícula de educación superior", 313583, "313.583", "matrículas", "2024-II", "Educación superior", "Escala", "Antioquia", "Registros de matrícula en programas ofertados en el departamento", "snies-bases-2024", "derivada", "Dimensionar el sistema comparable y sus cambios por nivel, sector y modalidad.", "Es el semestre con mayor total de 2024; no son personas únicas del año ni residentes necesariamente."),
    indicator("he-ies", "IES con matrícula activa", 73, "73", "instituciones", "2024-II", "Educación superior", "Oferta", "Antioquia", "IES con al menos un registro de matrícula en el corte", "snies-bases-2024", "derivada", "Identificar capacidad institucional efectivamente activa.", "Una IES puede operar en varios municipios; no equivale a sedes físicas."),
    indicator("he-municipalities", "Municipios con oferta activa", 51, "51 de 125", "municipios", "2024-II", "Educación superior", "Territorio", "Antioquia", "Municipios con matrícula de educación superior por lugar de oferta", "snies-bases-2024", "derivada", "Focalizar expansión, articulación y modalidades flexibles.", "Oferta local no equivale a cobertura de residentes; los estudiantes pueden desplazarse o estudiar virtualmente."),
    indicator("tuition-free", "Beneficiarios de gratuidad", 118000, "Más de 118.000", "beneficiarios", "2025-1", "Educación superior", "Acceso", "Antioquia", "Beneficiarios reportados por el MEN", "men-antioquia-2026", "directa", "Seguir la escala del apoyo financiero y formular preguntas de permanencia.", "Es un umbral publicado, no matrícula adicional ni resultado de graduación."),
    indicator("new-entry", "Nuevos ingresos de primer curso frente a 2022", 36091, "36.091", "ingresos adicionales", "Balance a 2025", "Educación superior", "Acceso", "Antioquia", "Nuevos estudiantes de primer ingreso reportados por el MEN respecto a 2022", "men-antioquia-2026", "directa", "Contrastar expansión reciente con la base departamental SNIES 2025 cuando esté disponible.", "El comunicado no desagrega institución, semestre ni método; no se suma a la matrícula SNIES."),
    indicator("college-at-school", "Educación Superior en tu Colegio", 2659, "2.659", "estudiantes", "Balance a 2025", "Transición media–superior", "Acceso", "Antioquia", "Estudiantes vinculados a la estrategia", "men-antioquia-2026", "directa", "Seguir la articulación y su conversión posterior a matrícula y graduación.", "Participar no equivale a transitar ni graduarse de educación superior."),
    indicator("semester-zero-students", "Jóvenes en Semestre Cero", 4247, "4.247", "estudiantes", "2026", "Transición media–superior", "Acceso", "61 municipios", "Estudiantes de grado 11 beneficiados por preparación académica", "gob-semestre-cero-2026", "directa", "Priorizar apoyos de transición y medir ingreso posterior.", "Beneficiarios de preparación, no nuevos matriculados en educación superior."),
    indicator("semester-zero-territory", "Cobertura municipal de Semestre Cero", 61, "61", "municipios", "2026", "Transición media–superior", "Territorio", "Antioquia", "Municipios participantes, incluidos 16 rurales dispersos", "gob-semestre-cero-2026", "directa", "Revisar equilibrio territorial del programa.", "Presencia del programa no mide intensidad ni resultados por municipio."),
    indicator("district-enrolment", "Matrícula de las tres IES distritales", 46489, "46.489", "matrículas", "2026-1", "Educación superior", "Escala", "Medellín", "ITM, Pascual Bravo y Colegio Mayor de Antioquia", "medellin-plan-2026", "directa", "Gestionar capacidad conjunta del sistema público distrital.", "Corte administrativo al 28 de febrero; no sustituye SNIES por programa."),
    indicator("district-accredited", "Programas acreditados vigentes en las IES distritales", 40, "40", "programas", "2026-02-28", "Educación superior", "Calidad", "Medellín", "ITM, Pascual Bravo y Colegio Mayor de Antioquia", "medellin-plan-2026", "directa", "Seguir calidad certificada y renovaciones próximas.", "Conteo consolidado del Plan Indicativo; programa acreditado no es lo mismo que registro calificado."),
    indicator("district-research", "Grupos A1, A o B de las IES distritales", 21, "21", "grupos", "2026-02-28", "Investigación", "Investigación", "Medellín", "ITM, Pascual Bravo y Colegio Mayor de Antioquia", "medellin-plan-2026", "directa", "Orientar cooperación y fortalecimiento de capacidades de investigación.", "El indicador distrital usa categorías seleccionadas; no representa todos los grupos reconocidos."),
    indicator("zero-tuition-benefits", "Beneficios proyectados de Matrícula Cero", 46667, "46.667", "beneficios", "2026-1", "Educación superior", "Acceso", "Medellín", "Convocatoria para ocho IES públicas", "medellin-matricula-cero-2026", "reportada", "Planear demanda potencial y recursos del programa.", "Proyección de beneficios: no son estudiantes únicos, matrícula adicional ni ejecución verificada."),
    indicator("research-groups", "Grupos reconocidos vinculados a Antioquia", 815, "815", "grupos", "Convocatoria 957", "Investigación", "Investigación", "Antioquia", "Grupos únicos asignados por GrupLAC o institución avaladora antioqueña", "minciencias-957-2025", "derivada", "Mapear capacidades científicas y cooperación institucional.", "El PDF nacional no incluye departamento; MaterIA deriva la ubicación con 90 % de cruce histórico y aval institucional para grupos nuevos."),
    indicator("school-students", "Estudiantes del sistema oficial departamental", 430000, "Cerca de 430.000", "estudiantes", "2026-II", "Preescolar, básica y media", "Escala", "116 municipios no certificados", "Matrícula en instituciones educativas oficiales administradas por el departamento", "gob-aulas-2026", "reportada", "Dimensionar la cantera educativa bajo gestión departamental.", "Cifra aproximada: excluye los nueve municipios certificados y no puede sumarse con el perfil del Valle de Aburrá."),
    indicator("school-teachers", "Docentes del sistema oficial departamental", 20000, "Cerca de 20.000", "docentes", "2026-II", "Preescolar, básica y media", "Capacidad", "116 municipios no certificados", "Docentes de instituciones educativas oficiales", "gob-aulas-2026", "reportada", "Dimensionar capacidad de acompañamiento y desarrollo docente.", "Cifra aproximada de comunicado; no incluye los municipios certificados."),
    indicator("extended-day", "Instituciones con Jornada Extendida", 552, "552", "instituciones educativas", "2026-II", "Preescolar, básica y media", "Permanencia", "116 municipios no certificados", "Instituciones educativas oficiales alcanzadas", "gob-aulas-2026", "directa", "Vincular tiempo escolar adicional con aprendizaje y permanencia.", "Cobertura institucional, no número de estudiantes ni evaluación de impacto."),
    indicator("education-connectivity-points", "Puntos de conectividad educativa", 2290, "2.290", "puntos", "2026-06", "Preescolar, básica y media", "Infraestructura", "Antioquia", "Puntos satelitales o de fibra en sedes educativas", "gob-conectividad-2026", "directa", "Priorizar mantenimiento, uso pedagógico y brechas de calidad del servicio.", "Punto conectado no garantiza disponibilidad continua, velocidad suficiente ni uso efectivo."),
    indicator("education-connectivity-students", "Estudiantes alcanzados por conectividad", 272000, "Cerca de 272.000", "estudiantes", "2026-06", "Preescolar, básica y media", "Infraestructura", "Antioquia", "Estudiantes beneficiados reportados por la Gobernación", "gob-conectividad-2026", "reportada", "Dimensionar alcance y exigir métricas de calidad y uso.", "Cifra aproximada de alcance; no mide usuarios únicos, continuidad ni aprendizaje."),
    indicator("literacy-children", "Niñas y niños en la alianza de alfabetización inicial", 17192, "17.192", "niñas y niños", "2025", "Preescolar, básica y media", "Aprendizaje", "Cinco subregiones", "Beneficiarios de preescolar a quinto en 507 sedes", "proantioquia-capacidades-2026", "directa", "Conectar aprendizajes fundamentales con trayectorias educativas completas.", "Beneficiarios reportados por la alianza; no es una medición de aprendizaje ni un efecto causal."),
    indicator("private-investment", "Inversión privada educativa reportada", 399655, "$399.655 millones", "millones de pesos", "2025", "Sistema educativo", "Inversión", "Nueve subregiones", "Inversión reportada por 55 organizaciones privadas", "proantioquia-inversion-2025", "reportada", "Mapear complementariedades y vacíos de financiación territorial.", "No es gasto público, ejecución auditada ni impacto. La muestra cambió frente a 2024, por lo que no se presenta como crecimiento interanual."),
    indicator("private-initiatives", "Iniciativas privadas sistematizadas", 297, "297", "iniciativas", "2025", "Sistema educativo", "Inversión", "Nueve subregiones", "Ocho categorías de inversión educativa", "proantioquia-inversion-2025", "directa", "Reducir duplicidades y conectar actores por territorio y propósito.", "Una iniciativa puede variar mucho en escala; contar proyectos no mide intensidad ni resultado."),
    indicator("valley-school-enrolment", "Matrícula escolar del Valle de Aburrá", 608362, "608.362", "estudiantes", "2025", "Preescolar, básica y media", "Escala", "Valle de Aburrá", "Matrícula escolar oficial y no oficial de la subregión", "proantioquia-valle-aburra-2026", "directa", "Dimensionar la concentración de la demanda futura y la articulación metropolitana.", "Universo escolar subregional; no se suma con los 430.000 estudiantes de municipios no certificados."),
    indicator("valley-school-sites", "Sedes educativas del Valle de Aburrá", 1352, "1.352", "sedes", "2025", "Preescolar, básica y media", "Infraestructura", "Valle de Aburrá", "Sedes oficiales y no oficiales", "proantioquia-valle-aburra-2026", "directa", "Mapear nodos para orientación, media técnica y articulación con educación superior.", "Sede no equivale a institución ni informa por sí sola capacidad o calidad."),
    indicator("snies-national-enrolment-2025", "Matrícula nacional de educación superior", 2723364, "2.723.364", "matrículas", "2025", "Educación superior", "Escala", "Colombia", "Resultado agregado nacional publicado por el MEN", "snies-national-2025", "directa", "Actualizar el contexto nacional sin atribuir el resultado a Antioquia.", "El comunicado no contiene la base departamental descargable; no se usa para recalcular Antioquia."),
    indicator("snies-national-coverage-legacy-2025", "Cobertura nacional con cálculo histórico", 61.75, "61,75 %", "porcentaje", "2025", "Educación superior", "Acceso", "Colombia", "Tasa nacional con la metodología poblacional usada históricamente", "snies-national-2025", "directa", "Mantener continuidad con la serie nacional anterior.", "No es la cobertura de Antioquia y no debe mezclarse con el cálculo actualizado de población."),
    indicator("snies-national-coverage-updated-2025", "Cobertura nacional con proyecciones DANE actualizadas", 56.55, "56,55 %", "porcentaje", "2025", "Educación superior", "Acceso", "Colombia", "Tasa nacional recalculada con nuevas proyecciones de población", "snies-national-2025", "directa", "Mostrar cómo cambia el indicador cuando cambia el denominador poblacional.", "No es una caída observada: es una metodología de denominador diferente a la serie histórica."),
    indicator("snies-national-tuition-free-2025", "Beneficiarios nacionales de gratuidad", 939282, "939.282", "beneficiarios", "2025", "Educación superior", "Acceso", "Colombia", "Beneficiarios reportados por el MEN en IES públicas", "snies-national-2025", "directa", "Dimensionar el programa nacional de gratuidad.", "Beneficiarios no equivalen a matrículas adicionales ni a graduados."),
    indicator("antioquia-coverage-2024", "Cobertura de educación superior de Antioquia", 57.42, "57,42 %", "porcentaje", "2024", "Educación superior", "Acceso", "Antioquia", "Tasa reportada en el Informe de Gestión 2025 de la Gobernación", "gob-gestion-educacion-2025", "directa", "Seguir el acceso departamental con la definición oficial del informe.", "Conserve el corte y la metodología del informe; no sustituye la razón propia de oferta por subregión."),
    indicator("antioquia-enrolment-change-2024", "Aumento reportado de matrícula frente al año anterior", 4475, "+4.475", "matrículas", "2024", "Educación superior", "Escala", "Antioquia", "Cambio reportado por la Gobernación en su Informe de Gestión 2025", "gob-gestion-educacion-2025", "directa", "Contrastar el repunte con la serie SNIES comparable.", "Cambio agregado reportado; no se distribuye por institución, nivel o municipio en esta cifra."),
    indicator("antioquia-tti-noncertified-2024", "Tránsito inmediato a educación superior", 34.90, "34,90 %", "porcentaje", "2024", "Transición media–superior", "Acceso", "116 municipios no certificados", "Bachilleres de los municipios no certificados según el informe departamental", "gob-gestion-educacion-2025", "directa", "Focalizar orientación, financiación y articulación media-superior.", "No representa Medellín ni los demás municipios certificados y no es comparable sin conservar ese universo."),
    indicator("antioquia-coverage-outside-valley-2024", "Cobertura fuera del Valle de Aburrá", 29.14, "29,14 %", "porcentaje", "2024 · seguimiento provisional", "Educación superior", "Territorio", "Antioquia sin Valle de Aburrá", "Indicador de seguimiento de la Agenda Antioquia 2040", "agenda-antioquia-2040-2025", "directa", "Hacer visible la brecha territorial metropolitana.", "Corte de seguimiento con metodología propia; no se resta automáticamente de la cobertura departamental posterior."),
    indicator("acv-unprepared-2024", "Jóvenes que no se sienten preparados para educación superior", 39, "39 %", "porcentaje", "ICV 2024", "Transición media–superior", "Percepción", "Antioquia", "Jóvenes encuestados en el Informe de Calidad de Vida", "acv-icv-2024", "reportada", "Orientar acciones de información, expectativas y preparación académica.", "Es una percepción de encuesta, no una medición de competencias ni un resultado administrativo."),
    indicator("acv-education-work-disconnect-2024", "Percepción de desconexión entre educación y trabajo", 70, "Cerca de 70 %", "porcentaje", "ICV 2024", "Trayectorias educativas", "Percepción", "Antioquia", "Personas jóvenes consultadas en el Informe de Calidad de Vida", "acv-icv-2024", "reportada", "Incorporar pertinencia e información laboral en orientación y diseño de oferta.", "Percepción aproximada de encuesta; no mide inserción laboral observada."),
    indicator("acv-youth-mainly-studying-2024", "Jóvenes de 17 a 21 cuya actividad principal es estudiar", 208693, "208.693", "personas", "2024", "Trayectorias educativas", "Acceso", "Antioquia", "Población de 17 a 21 años cuya actividad principal es estudiar", "acv-icv-2024", "directa", "Observar el espacio de participación educativa más allá de la matrícula por lugar de oferta.", "La categoría actividad principal no equivale a matrícula de educación superior; en 2019 eran 248.903."),
    indicator("palante-applicants-2025", "Inscritos a Becas Jóvenes Pa'Lante", 7462, "7.462", "inscritos", "Convocatoria 2025", "Educación para el Trabajo y el Desarrollo Humano", "Demanda", "123 municipios", "Personas inscritas al cierre de la convocatoria", "gob-palante-2025", "directa", "Medir demanda inicial y construir el embudo hasta matrícula y certificación.", "Inscripción no equivale a selección, legalización ni matrícula."),
    indicator("palante-women-applicants-2025", "Participación de mujeres entre inscritos", 63, "63 %", "porcentaje", "Convocatoria 2025", "Educación para el Trabajo y el Desarrollo Humano", "Equidad", "123 municipios", "Mujeres entre las personas inscritas", "gob-palante-2025", "directa", "Seguir acceso y resultados con enfoque de género.", "Composición de inscritos; no representa adjudicatarios ni graduados."),
    indicator("cgem-offer-combinations-2026", "Combinaciones de oferta de Jóvenes Pa'Lante", 165, "165", "combinaciones", "Oferta publicada 2026-07-09", "Educación para el Trabajo y el Desarrollo Humano", "Oferta", "Nueve subregiones", "Combinaciones únicas de sede, institución y programa extraídas del PDF", "cgem-offer-2026", "derivada", "Permitir búsqueda territorial y por área de la oferta pública.", "Una fila no es un cupo, una matrícula ni necesariamente un programa único."),
    indicator("cgem-offer-municipalities-2026", "Municipios en la oferta publicada", 78, "78", "municipios", "Oferta publicada 2026-07-09", "Educación para el Trabajo y el Desarrollo Humano", "Territorio", "Antioquia", "Municipios homologados desde 82 sedes o localidades del PDF", "cgem-offer-2026", "derivada", "Identificar disponibilidad territorial de la convocatoria.", "Presencia en la oferta no garantiza apertura del grupo ni matrícula efectiva."),
    indicator("cgem-offer-institutions-2026", "Instituciones con oferta publicada", 16, "16", "instituciones", "Oferta publicada 2026-07-09", "Educación para el Trabajo y el Desarrollo Humano", "Capacidad", "Antioquia", "Proveedores de formación homologados desde el PDF oficial", "cgem-offer-2026", "derivada", "Mapear operadores y concentración de la oferta.", "Institución aliada no equivale a IES activa en SNIES ni a grupo abierto."),
    indicator("palante-announced-scholarships-2026", "Becas anunciadas para Jóvenes Pa'Lante", 10000, "10.000", "becas", "Convocatoria 2026", "Educación para el Trabajo y el Desarrollo Humano", "Acceso", "Antioquia", "Meta anunciada por la Gobernación", "gob-palante-2026", "reportada", "Dimensionar la escala esperada y exigir seguimiento de adjudicación y matrícula.", "Meta anunciada: no equivale a beneficiarios seleccionados, legalizados o matriculados."),
    indicator("cgem-budget-total-2026", "Presupuesto inicial de la Corporación Gilberto Echeverri", 46291.208375, "$46.291 millones", "millones de pesos", "2026", "Financiación educativa", "Inversión", "Antioquia", "Presupuesto inicial de ingresos y gastos aprobado", "cgem-budget-2026", "directa", "Dimensionar la capacidad financiera administrada por la Corporación.", "Apropiación inicial; no es ejecución, impacto ni costo por beneficiario."),
    indicator("cgem-budget-scholarships-2026", "Apropiación inicial para becas", 33976.693277, "$33.977 millones", "millones de pesos", "2026", "Financiación educativa", "Inversión", "Antioquia", "Rubro Becas del presupuesto inicial", "cgem-budget-2026", "directa", "Relacionar escala presupuestal con adjudicación, matrícula y permanencia.", "Apropiación presupuestal; no se divide entre la meta de becas sin conocer ejecución y universo final."),
    indicator("cgem-budget-semester-zero-2026", "Apropiación inicial para Semestre Cero", 4927.057799, "$4.927 millones", "millones de pesos", "2026", "Transición media–superior", "Inversión", "Antioquia", "Rubro Semestre Cero del presupuesto inicial", "cgem-budget-2026", "directa", "Contrastar recursos, cobertura y transición efectiva posterior.", "Apropiación inicial, no ejecución ni evaluación de impacto."),
    indicator("matricula-cero-financing-2026-2", "Cobertura máxima de Matrícula Cero", 100, "Hasta 100 %", "porcentaje de la liquidación de matrícula", "Convocatoria 2026-2", "Pregrado", "Financiación", "Medellín", "Personas elegibles admitidas o matriculadas en IES públicas con convenio y sede en Medellín", "sapiencia-matricula-cero-2026-2", "directa", "Identificar una ruta local abierta de financiación y conectarla con admisión y permanencia.", "La postulación no garantiza el beneficio; aplican requisitos, impedimentos, validación y disponibilidad de recursos."),
    indicator("matricula-cero-minimum-credits-2026-2", "Créditos mínimos de Matrícula Cero", 8, "8", "créditos", "Convocatoria 2026-2", "Pregrado", "Permanencia", "Medellín", "Postulación y renovación del beneficio, con excepciones reglamentarias", "sapiencia-matricula-cero-2026-2", "directa", "Orientar la carga académica mínima y prevenir pérdida del beneficio.", "La fuente contempla excepciones para ciclos complementarios y los dos últimos semestres; consulte el reglamento completo."),
    indicator("basic-enrolment", "Matrícula de preescolar, básica y media", 1148645, "1.148.645", "matrículas", "2024", "Preescolar, básica y media", "Escala", "Antioquia", "Matrícula oficial y no oficial de preescolar a media, con ciclos de adultos en su nivel equivalente", "men-matricula-basica-2024", "derivada", "Dimensionar la base escolar que alimentará la demanda futura de educación superior.", "La serie no incluye 2018 (no existe en el dataset); cayó 17,9 % desde 2011 por demografía, no por cobertura."),
    indicator("basic-net-coverage-media", "Cobertura neta de educación media", 52.81, "52,8 %", "por ciento", "2024", "Preescolar, básica y media", "Acceso", "Antioquia", "Población en edad de media matriculada en media (fila departamental oficial)", "men-tasas-ebm-2024", "directa", "Ubicar el cuello de botella escolar previo a la educación superior.", "El salto 2017→2018 de la serie es un artefacto de la reestimación censal del denominador, no una mejora real."),
    indicator("basic-dropout-secondary", "Deserción intraanual en secundaria", 5.1, "5,1 %", "por ciento", "2024", "Preescolar, básica y media", "Permanencia", "Antioquia", "Estudiantes del sector oficial que abandonan durante el año escolar", "men-tasas-ebm-2024", "directa", "Focalizar retención donde la fuga duplica a los demás niveles.", "Tasa intraanual calculada por el MEN solo sobre la matrícula oficial."),
    indicator("bachelors-yearly", "Bachilleres graduados al año", 86837, "86.837", "bachilleres", "2024", "Transición media–superior", "Demanda", "Antioquia · 10 ETC", "Aprobados de grado 11 más ciclo 26 de adultos, sectores oficial y no oficial", "men-bachilleres-2024", "derivada", "Dimensionar la cosecha anual que puede transitar a educación superior.", "El año 2022 venía duplicado en el origen y se depuró fila a fila; incluye bachilleres adultos por CLEI."),
    indicator("icetex-new-credits", "Créditos ICETEX nuevos en Antioquia", 484, "484", "créditos", "2025", "Financiación educativa", "Financiación", "Antioquia", "Beneficiarios nuevos por departamento de origen", "icetex-datos-abiertos-2026", "directa", "Medir el repliegue del crédito educativo como vía de acceso.", "Cayó 84,7 % frente a 2024; el dataset no publica montos (solo deciles) y las renovaciones apenas variaron."),
    indicator("icetex-arrears-share", "Créditos ICETEX en mora (época de amortización)", 28.9, "28,9 %", "por ciento", "2026-06-30", "Financiación educativa", "Financiación", "Antioquia", "Créditos activos de residentes en Antioquia que ya amortizan", "icetex-datos-abiertos-2026", "derivada", "Dimensionar la carga que dejó el modelo de crédito educativo.", "Cálculo propio sobre conteos; el indicador oficial de cartera vencida (saldo con mora >30 días) es 14,9 %."),
    indicator("gob-scholarships-total", "Becas históricas de la Gobernación", 14566, "14.566", "beneficiarios", "2013-2024", "Financiación educativa", "Equidad", "Antioquia · 9 subregiones", "Beneficiarios acumulados del programa departamental de becas; 81,6 % de estratos 1 y 2", "gob-becas-2013-2024", "directa", "Leer a quién llegó la beca pública y su colapso reciente (43 nuevas en 2024).", "Base congelada desde mayo de 2024; 2024 es parcial."),
    indicator("gob-scholarships-graduation", "Graduación de becarios de la Gobernación", 59.4, "59,4 %", "por ciento", "Cohortes 2013-2018", "Financiación educativa", "Permanencia", "Antioquia", "Becarios de cohortes con al menos seis años al corte de la base", "gob-becas-2013-2024", "derivada", "Aproximar la efectividad de la beca como vía de graduación.", "La foto de graduación es a mayo de 2024 sin fecha de grado; las cohortes recientes aún no alcanzan a graduarse."),
    indicator("sena-apprentices", "Aprendices SENA en fichas vigentes", 168420, "168.420", "aprendices", "feb-2024", "Sistema educativo", "Escala", "Regional Antioquia", "Fichas vigentes de titulada (90.156) y cursos especiales y eventos (78.264)", "sena-fpi-2024", "directa", "Dimensionar el otro sistema de formación con su registro propio.", "Foto al corte que acumula cohortes de varios años; no comparable con matrícula SNIES de semestre pico; la complementaria corta regular no está."),
    indicator("ole-programs-published", "Programas con retorno salarial publicado", 1044, "1.044", "programas × IES", "IBC 2023", "Educación superior", "Oferta", "IES con domicilio en Antioquia", "Cruces programa-institución con 20 o más cotizantes en la Base IBC 2023", "ole-base-ibc-2023", "derivada", "Comparar el salario de enganche programa a programa, no solo por área.", "El IBC se estima desde siete rangos salariales (el superior está censurado) y cada cotizante cuenta en su máximo nivel de formación."),
]


COMPARABILITY_RULES = [
    {
        "title": "Matrícula comparable ≠ señal reciente",
        "text": "SNIES 2024-II permite comparar instituciones, programas y municipios. Los cortes 2025–2026 de gobiernos y programas son señales administrativas con otra definición.",
    },
    {
        "title": "Beneficios ≠ estudiantes adicionales",
        "text": "Gratuidad, Matrícula Cero, Semestre Cero y Educación Superior en tu Colegio reportan beneficiarios, beneficios o participantes; no se suman a la matrícula.",
    },
    {
        "title": "Territorios no aditivos",
        "text": "Los 116 municipios no certificados y el Valle de Aburrá tienen universos que se superponen de forma distinta; sus matrículas escolares nunca se suman.",
    },
    {
        "title": "Inversión reportada ≠ impacto",
        "text": "El balance privado describe recursos e iniciativas informados por 55 organizaciones. La muestra cambió y no demuestra ejecución auditada ni resultados causales.",
    },
    {
        "title": "Oferta publicada ≠ cupos ni matrícula",
        "text": "Las 165 filas de Jóvenes Pa'Lante son combinaciones de sede, institución y programa. La apertura depende de demanda mínima y condiciones operativas.",
    },
    {
        "title": "Presupuesto inicial ≠ ejecución",
        "text": "Los $46.291 millones aprobados para la Corporación dimensionan capacidad financiera, pero no se dividen entre beneficiarios ni prueban resultados.",
    },
]


UPDATE_QUEUE = [
    {
        "date": "Cuando aparezca la base consolidada",
        "title": "Desagregación departamental SNIES 2025",
        "action": "El agregado nacional ya fue publicado. Descargar la base por departamento, recalcular Antioquia y sustituir el corte comparable solo después de pasar la auditoría.",
        "source_id": "snies-national-2025",
    },
    {
        "date": "Cuando exista base pública",
        "title": "Permanencia y graduación de Antioquia",
        "action": "Integrar SPADIES/OTE por cohorte, IES, nivel y modalidad sin usar referencias nacionales como resultado local.",
        "source_id": "snies-bases-2024",
    },
    {
        "date": "Cuando el SENA publique un corte posterior a feb-2024",
        "title": "Serie SENA actualizada",
        "action": "Reemplazar la foto de fichas vigentes por el corte nuevo y revisar si aparece la complementaria corta regular.",
        "source_id": "sena-fpi-2024",
    },
    {
        "date": "Cuando el OLE publique el corte 2024",
        "title": "Retorno por programa con IBC 2024",
        "action": "Regenerar ole_programas.js con la vigencia nueva y recalcular la calibración por área antes de publicar.",
        "source_id": "ole-base-ibc-2023",
    },
    {
        "date": "Si el MEN lo publica",
        "title": "Tránsito inmediato por municipio y ETC",
        "action": "No existe dataset vivo (verificado jul-2026); integrarlo apenas exista para volver territorial la cifra de 44,23 %.",
        "source_id": "men-bachilleres-2024",
    },
    {
        "date": "Próxima publicación",
        "title": "Línea base Antioquia First",
        "action": "Añadir inglés con un estándar común para los 125 municipios cuando Proantioquia publique resultados y metadatos.",
        "source_id": "proantioquia-capacidades-2026",
    },
]


def validate() -> dict:
    source_ids = [source["id"] for source in SOURCES]
    indicator_ids = [item["id"] for item in INDICATORS]
    assert len(source_ids) == len(set(source_ids)), "Hay fuentes duplicadas"
    assert len(indicator_ids) == len(set(indicator_ids)), "Hay indicadores duplicados"
    assert all(item["source_id"] in source_ids for item in INDICATORS), "Indicador sin fuente"
    assert all(item["value"] >= 0 for item in INDICATORS), "Valor negativo inesperado"
    assert all(source["url"].startswith("https://") for source in SOURCES), "URL no segura"
    assert all(item["caveat"] and item["universe"] for item in INDICATORS), "Falta universo o cautela"
    return {
        "status": "correcto",
        "source_reference_errors": 0,
        "duplicate_source_ids": 0,
        "duplicate_indicator_ids": 0,
        "missing_universes": 0,
        "missing_caveats": 0,
    }


def main() -> None:
    checks = validate()
    source_counts = Counter(source["source_type"] for source in SOURCES)
    evidence_counts = Counter(item["evidence"] for item in INDICATORS)
    payload = {
        "meta": {
            "title": "Fuentes vivas de educación en Antioquia",
            "version": "V35",
            "research_cut": CUT.isoformat(),
            "method": "Curaduría de fuentes primarias y observatorios reconocidos; cada cifra conserva periodo, territorio, universo, tipo de evidencia, uso y cautela.",
            "latest_comparable_higher_ed_cut": "2024-II",
            "next_expected_release": "SNIES 2025 · agregado nacional publicado; base departamental consolidada pendiente",
        },
        "summary": {
            "sources": len(SOURCES),
            "official_sources": source_counts["oficial"],
            "observatory_sources": source_counts["observatorio"],
            "indicators": len(INDICATORS),
            "evidence": dict(evidence_counts),
        },
        "sources": SOURCES,
        "indicators": INDICATORS,
        "comparability_rules": COMPARABILITY_RULES,
        "update_queue": UPDATE_QUEUE,
        "validation": checks,
    }
    OUTPUT.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"output": str(OUTPUT), **payload["summary"], **checks}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
